"""empty message

Revision ID: 008956026ba3
Revises: 8ffc56e173c1
Create Date: 2022-12-19 08:44:05.326216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008956026ba3'
down_revision = '8ffc56e173c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
