"""empty message

Revision ID: 3bb7b73cfe2c
Revises: 6ff99bef2bfb
Create Date: 2022-12-17 11:09:45.888402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb7b73cfe2c'
down_revision = '6ff99bef2bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint("email", 'users', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email", 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
